"""Pure-logic core for the terragrunt-pr-merge-workflow feature.

This module holds the input-varying behavior of the detect stage:

- ``filter_leaves`` -- the anchored path filter that keeps only leaf units.
- ``parse_leaf``    -- the Path_Parser that derives tenant / workDir per leaf.
- ``build_matrix``  -- the matrix builder (256 cap + empty-set handling).
- ``classify_source`` -- the Source_Scheme classifier (https / ssh / unrecognized).

These functions are deliberately pure so they can be property/unit tested off
the CI runner. The GitHub Actions workflow feeds the change set (from
``git diff``) into these functions via a thin CLI wrapper.

The bodies below are placeholders scaffolded by Task 1; subsequent tasks
(2-6) implement the real behavior alongside their property tests.
"""

from __future__ import annotations

import json
import re
import sys

# Anchored leaf-unit pattern: exactly ``<tenant>/<env>/terragrunt.hcl`` where
# ``<tenant>`` and ``<env>`` are each one path segment of ASCII letters/digits.
# Anchoring plus the literal ``terragrunt.hcl`` filename guarantees:
#   - ``root.hcl`` at any depth never matches (wrong filename);
#   - a repo-root ``terragrunt.hcl`` never matches (no ``<tenant>/<env>`` prefix);
#   - deep paths like ``a/b/c/terragrunt.hcl`` never match (too many segments).
_LEAF_PATTERN = re.compile(r"^[A-Za-z0-9]+/[A-Za-z0-9]+/terragrunt\.hcl$")


def filter_leaves(paths: list[str]) -> list[str]:
    """Return only the paths that are leaf Terragrunt units.

    A leaf unit path matches ``^[A-Za-z0-9]+/[A-Za-z0-9]+/terragrunt\\.hcl$``.
    Input order is preserved and duplicates are removed (first occurrence wins).

    Requirements: 2.1, 2.2, 2.3, 3.2
    """
    kept: list[str] = []
    seen: set[str] = set()
    for path in paths:
        if path in seen:
            continue
        if _LEAF_PATTERN.match(path):
            kept.append(path)
            seen.add(path)
    return kept


class MalformedLeafPathError(ValueError):
    """Raised when a leaf path has fewer than two segments before the filename.

    A well-formed leaf path is ``<tenant>/<envDir>/terragrunt.hcl`` -- i.e. it
    has at least two directory segments before the trailing file name. The
    filter (``filter_leaves``) only admits well-formed paths, so this error is a
    defensive guard for callers that invoke ``parse_leaf`` directly.

    Requirements: 4.4
    """


def parse_leaf(path: str) -> dict:
    """Derive per-leaf fields (tenant, envDir, workDir, leafPath) from a path.

    Splits the leaf path on ``/`` and derives:

    - ``tenant``   -- the first path segment (Req 4.1);
    - ``envDir``   -- the second path segment, carried for reporting only;
    - ``workDir``  -- the parent directory of the leaf file, i.e. the path with
      ``/terragrunt.hcl`` removed -> ``<tenant>/<envDir>`` (Req 4.2);
    - ``leafPath`` -- the input path unchanged.

    No environment name is derived or validated beyond carrying ``envDir``
    verbatim (Req 4.3). A path with fewer than two segments before the file
    name is malformed and raises :class:`MalformedLeafPathError` (Req 4.4).

    Requirements: 4.1, 4.2, 4.3, 4.4
    """
    segments = path.split("/")
    # A well-formed leaf has at least two directory segments before the file
    # name, i.e. tenant, envDir, and the file itself (3+ segments total).
    if len(segments) < 3:
        raise MalformedLeafPathError(
            f"path is malformed: expected '<tenant>/<envDir>/<file>', got {path!r}"
        )

    tenant = segments[0]
    env_dir = segments[1]
    # workDir is the parent directory of the leaf file: the leaf path with the
    # trailing '/<filename>' removed. Per the leaf pattern this is
    # '<tenant>/<envDir>'.
    work_dir = "/".join(segments[:-1])

    return {
        "tenant": tenant,
        "envDir": env_dir,
        "workDir": work_dir,
        "leafPath": path,
    }


# GitHub Actions caps the number of jobs generated by a single matrix at 256
# per workflow run. The builder enforces this explicitly so an oversized change
# set fails loudly in the detect stage rather than being rejected opaquely by
# GitHub after some legs may already have started.
MAX_MATRIX_SIZE = 256


class MatrixSizeExceededError(ValueError):
    """Raised when the number of matched leaf units exceeds the matrix cap.

    GitHub Actions rejects matrices larger than 256 jobs. The matrix builder
    detects this condition up front and refuses to emit a partial or oversized
    matrix, failing the detect stage before any provision leg starts.

    Requirements: 5.3
    """


def build_matrix(paths: list[str]) -> tuple[list[dict], bool]:
    """Build the ``(entries, has_units)`` matrix from a list of changed paths.

    Composes :func:`filter_leaves` (keep only leaf-unit paths, de-duplicated and
    order-preserving) with :func:`parse_leaf` (derive ``tenant``, ``envDir``,
    ``workDir``, ``leafPath`` per leaf) to produce the matrix entries.

    - zero matches -> ``([], False)`` so the provision job is skipped
      (Req 5.4);
    - 1..256 matches -> ``(entries, True)`` with one entry per leaf
      (Req 5.1, 5.2), every entry carrying ``tenant``, ``workDir`` and
      ``leafPath`` (Req 5.5);
    - more than 256 matches -> raise :class:`MatrixSizeExceededError` with a
      "maximum matrix size exceeded" message and emit no matrix (Req 5.3).

    Requirements: 5.1, 5.2, 5.3, 5.4, 5.5
    """
    leaves = filter_leaves(paths)

    if not leaves:
        return ([], False)

    if len(leaves) > MAX_MATRIX_SIZE:
        raise MatrixSizeExceededError(
            "maximum matrix size exceeded: "
            f"{len(leaves)} leaf units matched, but the limit is "
            f"{MAX_MATRIX_SIZE}"
        )

    entries = [parse_leaf(leaf) for leaf in leaves]
    return (entries, True)


def classify_source(source: str) -> str:
    """Classify a Terragrunt ``source`` string by its transport prefix.

    The classification depends only on the transport prefix and never on the
    repository, path, or ``?ref=`` portion:

    - ``"https"`` when the source begins with ``git::https://``;
    - ``"ssh"`` when the source begins with ``git::git@`` or ``git::ssh://``;
    - ``"unrecognized"`` otherwise.

    Requirements: 9.1
    """
    if source.startswith("git::https://"):
        return "https"
    if source.startswith("git::git@") or source.startswith("git::ssh://"):
        return "ssh"
    return "unrecognized"


def _read_paths(stream) -> list[str]:
    """Read newline-delimited changed paths from a text stream.

    Blank lines and surrounding whitespace are ignored so that a trailing
    newline (or a completely empty stdin) yields an empty list rather than a
    spurious empty-string "path".
    """
    paths: list[str] = []
    for line in stream:
        stripped = line.strip()
        if stripped:
            paths.append(stripped)
    return paths


def _format_outputs(entries: list[dict], has_units: bool) -> str:
    """Render the detect-job outputs as GITHUB_OUTPUT-compatible lines.

    Emits two lines::

        matrix=<compact-json-array>
        has_units=<true|false>

    ``matrix`` is compact JSON (no spaces) so it round-trips cleanly through
    ``fromJSON(...)`` in the workflow, and ``has_units`` is the lowercase
    boolean literal GitHub Actions expressions compare against.
    """
    matrix_json = json.dumps(entries, separators=(",", ":"))
    has_units_literal = "true" if has_units else "false"
    return f"matrix={matrix_json}\nhas_units={has_units_literal}\n"


def main(argv: list[str] | None = None, stdin=None, stdout=None, stderr=None) -> int:
    """CLI entry point: stdin (newline-delimited paths) -> stdout (detect outputs).

    Reads the change set from ``stdin``, builds the matrix via
    :func:`build_matrix`, and writes the ``detect``-job outputs (``matrix`` and
    ``has_units``) to ``stdout`` in GITHUB_OUTPUT-compatible form.

    - empty input -> ``matrix=[]`` / ``has_units=false`` and exit 0
      (Req 2.5, 3.4, 5.4);
    - 1..256 matches -> the JSON matrix and ``has_units=true`` and exit 0
      (Req 5.5);
    - more than 256 matches -> a clear message on stderr and a non-zero exit,
      emitting no matrix (Req 5.3).

    Requirements: 2.5, 3.4, 5.3, 5.4, 5.5
    """
    stdin = stdin if stdin is not None else sys.stdin
    stdout = stdout if stdout is not None else sys.stdout
    stderr = stderr if stderr is not None else sys.stderr

    paths = _read_paths(stdin)

    try:
        entries, has_units = build_matrix(paths)
    except MatrixSizeExceededError as exc:
        # Fail loudly before emitting any matrix so the detect job stops the
        # provision fan-out entirely.
        print(f"::error::{exc}", file=stderr)
        return 1

    stdout.write(_format_outputs(entries, has_units))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
